### ISSUE TITLE
Make stand-alone option? (request)

### ISSUE THREAD

**Issue by rpgoldman** [Bioprotocols/PAML-specification#1]
Would it be possible for you to commit the UML diagrams in here to make it stand-alone buildable?  Then people who have all the supporting stuff could still build the diagrams themselves, but someone just tex-formatting and editing would not have to?

**Comment by jakebeal** [comment]
I thought I already had them in; looks like maybe I forgot a push. Can you let me know what's missing still?

**Comment by rpgoldman** [comment]
I didn't even try -- the message in the README indicated that I would need all the other repos checked out. If that's no longer necessary maybe update the README?

**Comment by jakebeal** [comment]
I guess the README didn't say anything one way or another about the LaTeX. I've updated the README to fix that.

**Comment by jakebeal** [comment]
Are you still having difficulty? If not, I will close this issue.

**Comment by rpgoldman** [comment]
No -- I think it was just a readme problem.
