### ISSUE TITLE
Should this repo have a PDF or link to the PDF?

### ISSUE THREAD

**Issue by Zulko** [Bioprotocols/PAML-specification#8]
Should this repo have a PDF or link to the PDF? It would make it easier for those of us who don't have LaTeX ready on their computer.

**Comment by jakebeal** [comment]
I think we don't want to accumulate lots of PDF diffs in the git, so we probably should do something like the automated LaTeX build that SBOL visual uses. I've opened a new issue for doing that (#9).

As a stopgap, I've added a snapshot of the current draft: https://github.com/SD2E/PAML-specification/blob/main/PAML-specification-snapshot-211011.pdf

**Comment by Zulko** [comment]
Perfect, thank you! :+1:
